name: Deploy Frontend App

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build Dcoker Image
    uses: ./.github/workflows/job-dockerize.yml

  test:
    name: Run tests
    needs: build
    uses: ./.github/workflows/job-test.yml

  deploy:
    name: Deploy to EB
    needs: test
    uses: ./.github/workflows/job-deploy.yml
