name: Test debug frontend app

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: docker run -e CI=true kbmegha/docker-react npm run test
