name: Deploy to EB

on: workflow_call

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Repository
        uses: actions/checkout@v4

      - name: Debug current directory
        run: pwd && ls -al

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
          application_name: fontend
          environment_name: Fontend-env-2
          existing_bucket_name: elasticbeanstalk-eu-north-1-324037294229
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
